import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { relative, sep } from 'node:path';

const dist = new URL('../dist/', import.meta.url);
const swUrl = new URL('sw.js', dist);

async function filesIn(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(entries.map(async entry => {
    const entryUrl = new URL(`${entry.name}${entry.isDirectory() ? '/' : ''}`, directory);
    return entry.isDirectory() ? filesIn(entryUrl) : [entryUrl];
  }));
  return nested.flat();
}

const fileUrls = (await filesIn(dist)).filter(file => file.href !== swUrl.href);
const precache = await Promise.all(fileUrls.map(async file => {
  const contents = await readFile(file);
  return { path: `/${relative(dist.pathname, file.pathname).split(sep).join('/')}`, contents };
}));
precache.sort((left, right) => left.path.localeCompare(right.path));
const release = createHash('sha256').update(precache.map(file => `${file.path}:${createHash('sha256').update(file.contents).digest('hex')}`).join('\n')).digest('hex').slice(0, 12);
const assets = JSON.stringify(precache.map(file => file.path));

await writeFile(swUrl, `/* Generated by scripts/build-sw.mjs. Do not edit this release artifact. */
const RELEASE = ${JSON.stringify(release)};
const CACHE = \`graphite-shell-\${RELEASE}\`;
const PRECACHE = ${assets};

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', event => {
  event.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(key => key.startsWith('graphite-shell-') && key !== CACHE).map(key => caches.delete(key))))
    .then(() => self.clients.claim()));
});

self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== location.origin) return;
  if (event.request.mode === 'navigate') {
    event.respondWith(fetch(event.request).then(response => {
      if (response.ok) caches.open(CACHE).then(cache => cache.put('/index.html', response.clone()));
      return response;
    }).catch(() => caches.match('/index.html')));
    return;
  }
  event.respondWith(caches.match(event.request).then(cached => cached || fetch(event.request).then(response => {
    if (response.ok && PRECACHE.includes(new URL(event.request.url).pathname)) caches.open(CACHE).then(cache => cache.put(event.request, response.clone()));
    return response;
  })));
});
`);
